---
project: word-of-the-day
default-region: us-west-2
code-bucket: gordon-word-of-the-day-c8482ea6
apps:
  - gordon.contrib.lambdas
  - lambda
events:
  every_morning:
    schedule_expression: cron(1 0 * * ? *)
    state: ENABLED
    description: Call lambda every morning.
    targets:
      download_word:
        lambda: lambda.word_fetcher
