AWSTemplateFormatVersion: '2010-09-09'
Description: 'An Alexa Flash Briefing skill website hosted on Amazon S3 and served via Amazon CloudFront.'
Mappings:
  Region2S3WebsiteSuffix:
    us-east-1:
      Suffix: ".s3-website-us-east-1.amazonaws.com"
    us-west-1:
      Suffix: ".s3-website-us-west-1.amazonaws.com"
    us-west-2:
      Suffix: ".s3-website-us-west-2.amazonaws.com"
    eu-west-1:
      Suffix: ".s3-website-eu-west-1.amazonaws.com"
    ap-northeast-1:
      Suffix: ".s3-website-ap-northeast-1.amazonaws.com"
    ap-northeast-2:
      Suffix: ".s3-website-ap-northeast-2.amazonaws.com"
    ap-southeast-1:
      Suffix: ".s3-website-ap-southeast-1.amazonaws.com"
    ap-southeast-2:
      Suffix: ".s3-website-ap-southeast-2.amazonaws.com"
    ap-south-1:
      Suffix: ".s3-website-ap-south-1.amazonaws.com"
    sa-east-1:
      Suffix: ".s3-website-sa-east-1.amazonaws.com"
    cn-north-1:
      Suffix: ".s3-website.cn-north-1.amazonaws.com.cn"
    eu-central-1:
      Suffix: ".s3-website-eu-central-1.amazonaws.com"
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketName: 
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - '-'
          - Ref: AWS::AccountId
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for s3-alexa-flash-briefing-site
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Origins:
        - CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
          DomainName:
            Fn::Join:
            - ''
            - - Ref: S3BucketForWebsiteContent
              - Fn::FindInMap:
                - Region2S3WebsiteSuffix
                - Ref: AWS::Region
                - Suffix
          Id: only-origin
Outputs:
  WebsiteURL:
    Value:
      Fn::Join:
      - ''
      - - http://
        - !GetAtt WebsiteCDN.DomainName
    Description: The URL of the newly created website
  BucketName:
    Value:
      Ref: S3BucketForWebsiteContent
    Description: Name of S3 bucket to hold website content

