AWSTemplateFormatVersion: '2010-09-09'
Description: 'An Alexa Flash Briefing skill website hosted on Amazon S3 and served via Amazon CloudFront.'
Mappings:
  Region2S3WebsiteSuffix:
    us-east-1:
      Suffix: ".s3-website-us-east-1.amazonaws.com"
    us-west-1:
      Suffix: ".s3-website-us-west-1.amazonaws.com"
    us-west-2:
      Suffix: ".s3-website-us-west-2.amazonaws.com"
    eu-west-1:
      Suffix: ".s3-website-eu-west-1.amazonaws.com"
    ap-northeast-1:
      Suffix: ".s3-website-ap-northeast-1.amazonaws.com"
    ap-northeast-2:
      Suffix: ".s3-website-ap-northeast-2.amazonaws.com"
    ap-southeast-1:
      Suffix: ".s3-website-ap-southeast-1.amazonaws.com"
    ap-southeast-2:
      Suffix: ".s3-website-ap-southeast-2.amazonaws.com"
    ap-south-1:
      Suffix: ".s3-website-ap-south-1.amazonaws.com"
    sa-east-1:
      Suffix: ".s3-website-sa-east-1.amazonaws.com"
    cn-north-1:
      Suffix: ".s3-website.cn-north-1.amazonaws.com.cn"
    eu-central-1:
      Suffix: ".s3-website-eu-central-1.amazonaws.com"
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketName: 
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - '-'
          - Ref: AWS::AccountId
# Removed CDN due to this http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ReplacingObjectsSameName.html
Outputs:
  WebsiteURL:
    Value:
      Fn::Join:
      - ''
      - - http://
        - Ref: S3BucketForWebsiteContent
        - Fn::FindInMap:
          - Region2S3WebsiteSuffix
          - Ref: AWS::Region
          - Suffix
    Description: The URL of the newly created website
  BucketName:
    Value:
      Ref: S3BucketForWebsiteContent
    Description: Name of S3 bucket to hold website content

